window.READING_DATA = [
  {
    "id": "r1",
    "title": "리딩1. The Cambrian Explosion",
    "paragraphs": [
      "Scientists have asked important questions about the Cambrian explosion for more than a century. Why did it occur so late in the history of Earth? The origin of multi cellular forms of life seems a relatively simple step compared to the origin of life itself. Why does the fossil record not document the series of evolutionary changes during the evolution of animals? Why did animal life evolve so quickly? Paleontologists continue to search the fossil record for answers to these questions.",
      "One interpretation regarding the absence of fossils during this important 100 million year period is that early animals were softy bodied and simply did not fossilize. (■) Fossilization of soft -bodied animals is less likely than fossilization of hard -bodied animals, but it does occur. (■) Conditions that promote fossilization of soft -bodied animals include very rapid covering by scientists that create an environment that discourages decomposition. (■) In fact, fossil beds containing soft bodied animals have been known for many years. (■)",
      "The Ediacara fossil formation, which contains the oldest known animal fossils, consists exclusively of soft-bodied forms. Although named after a site in Australia, the Ediacara formation is worldwide in distribution and dates to Precambrian times. This 700 - million-year-old formation gives few clues to the origins of modern animals, however, because paleontologists believe it represents an evolutionary experiment that failed. It contains no ancestors of modern animal groups."
    ],
    "questions": [
      "1. According to paragraph, which of the following is NOT a question that paleontologists asked about the Cambrian explosion? a. Why was the origin of life a simple ste p in Earth’s history? b. Why did it take so long for multicellular organisms to develop? c. Why did animal life evolve so rapidly? d. Why does the fossil record lack evidence of animal evolution during that time?",
      "2. Which of the following describes the relationship between paragraph 1 and paragraph 2? a. Paragraph 1 puts forward several scientific claims, one of which is rejected in paragraph 2. b. Paragraph 1 poses several questions, and paragraph",
      "3. offers a possible answer to one of them. c. Paragr aph 1 presents outdated traditional views, while paragraph 2 presents the current scientific conclusions. d. Paragraph 1 introduces a generalization that is illustrated by specific examples in paragraph 2.",
      "4. Look at the four squares [■] that indicate wh ere the following sentence could be added to the passage. It is relatively rare because the fossilization of soft - bodied animals requires a special environment.",
      "5. Which of the followin g is NOT mentioned in paragraph as being true of the Ediacara formation? a. It contains fossils that date back to the Precambrian period. b. It contains only soft-bodied animal fossils c. It is located on a single site in Australia. d. It does not contain any fossils of the ancestors of modern animals."
    ]
  },
  {
    "id": "r2",
    "title": "리딩2. Industrial Melanism in Peppered Moths",
    "paragraphs": [
      "While evolution usually occurs over thousands of years, sometimes the environmental pressure is so extreme that the rate speeds up. For the peppered moths, their motivation to adapt was increased predation. Peppered moths in England typically come in two different morphs or types that are determined by their genes. The more commonly seen morph was grey, often with “speckled” patterns that helped it blend in with light colored tree bark and lichens. The less common ly observed morph had a much higher melanin content, which makes its body and wings dark grey to black in color. However, the melanic trait is actually the dominant allele. The lighter morphs were more common because they could blend in more easily, making it more difficult for birds to see and then eat them. But, something shifted the situation in favor of the melanic morph.",
      "During the Industrial Revolution in England, air pollution in the form of soot from burned coal increased dramatically. This pollut ion eventually became so severe that thousands of people in London died from breathing it. This pollution also affected the peppered moths. Throughout England, but particularly in cities, the rocks and trees that the moths rested on became covered in a layer of soot, killing much of the lichen and making everything darker. Prior to industrialization, the melanic morph only accounted for about .01% of the moth population, by the middle of the 19th century it had increased noticeably, and by 1895 it had reach ed a staggering 98% in some areas, which puzzled many naturalists."
    ],
    "questions": [
      "1. The word “speckled” in paragraph 1 is closest in meaning to A. naked B. striped C. lessened D. spotted",
      "2. According to paragraph, which of the following is mentioned as the factor th at accelerated the pace of evolution? A. Introduction of a new predator B. A sudden change in the environment C. Genetic diseases and mutations D. Competition for resources",
      "3. All of the following are mentioned in paragraph 2 EXCEPT A. the influence of air pollution on human lives B. how the pollution changed the natural environment C. the number of peppered moths which died from air pollution D. the radical change in population of the melanic morph",
      "4. Based on paragraph, what can be inferred abou t the peppered moths in the middle of the 19th century? A. Light colored moths were less resistant to air pollution than darker ones. B. The Industrial Revolution threatened their survival and reproduction. C. There was a rapid increase in the moth popu lation due to industrialization. D. Their color had changed so that they could blend in with the surroundings."
    ]
  },
  {
    "id": "r3",
    "title": "리딩3. The Surface of Mars",
    "paragraphs": [
      "The surface of Mars shows a wide range of geologic features, including huge volcanoes -the largest known in the solar system -and extensive impact cratering. Three very large volcanoes are found on the Tharsis bulge, an “enormous“ geologic area near Mars's equator. The great height of Martian volcanoes is a direct consequence of the planet's low surface gravity. As lava flows and spreads to form a shield volcano, the volcano's eventual height depends on the new mountain's ability to support its own weight. The lower the gravity, the lesser the weight and the greater the height of the mountain. It is no accident that Maxwell Mons on Venus and the Hawaiian shield volcanoes on Earth rise to about the same height above their respective ba ses-Earth and Venus have similar surface gravity. Mars's surface gravity is only 40 percent that of Earth, so volcanoes rise roughly 2.5 times as high.",
      "Another prominent feature of Mars's surface is cratering. The Mariner spacecraft found that the surface of Mars, as well as that of its two moons, is pitted with impact craters formed by meteoroids falling in from space. As on our Moon, the smaller craters are often filled with surface matter -mostly dust-confirming that Mars is a dry desert world. However, Martian craters get filled in considerably faster than their lunar counterparts. On Mars, there are relatively few craters less than 5 kilometers in diameter. The Martian atmosphere is an efficient erosive agent, with Martian winds transporting dust from place to place and erasing surface features much faster than meteoritic impacts alone can obliterate them.",
      "The detailed appearance of Martian impact craters provides an important piece of information about conditions just below the planet's surface. Marti an craters are surrounded by ejecta that looks quite different from its lunar counterparts. A comparison of the Copernicus crater on the Moon with the (fairly typical) crater Yuty on Mars demonstrates the differences. The ejecta surrounding the lunar crate r is just what one would expect from an explosion ejecting a large volume of dust, soil, and boulders.",
      "However, the ejecta on Mars gives the distinct impression of a liquid that has splashed or flowed out of crater. Geologists think that this fluidized eje cta crater indicates that a layer of permafrost, or water ice, lies just a few meters under the surface. Explosive impacts heated and liquefied the ice, resulting in the fluid appearance of the ejecta."
    ],
    "questions": [
      "1. The word “enormous“ in the passage is closest in meaning to a) important b) extremely large c) Highly unusual d) active",
      "2. In paragraph, why does the author compare Maxwell Mons on Venus to the Hawaiian shield volcanoes on Earth? a) To help explain the relationship between surface gravity and volcano height b) To explain why Mars’s surface gravity is only 40 percent of Earth’s c) To point out differences between the surface gravity of Earth and the surface gravity of Venus d) To argue that there are more similarities than differences between volcanoes on different planets",
      "3. According to paragraph, what is demonstrated by the fact that craters fill in much faster on Mars than on the Moon? a) Erosion from meteoritic impacts takes place more quickly on Mars that on the Moon b) There is more dust on Mars than on the Moon. c) The surface of Mars is a dry desert. d) Wind is a powerful eroding force on Mars.",
      "4. According to paragraph , the ejecta of Mars’s crater Yuty differs from the ejecta of the Moon’s Copernicus crater in that the ejecta of the Yuty crater a) Has now become part of a permafrost layer b) Contains a large volume of dust, soil and boulders c) Suggests that liquid once came out of the surface at the crater site d) Was thrown a comparatively long distance from the center of the crater"
    ]
  },
  {
    "id": "r4",
    "title": "리딩4. Moving into Pueblos",
    "paragraphs": [
      "In the Mesa Verde area of the ancient North American Southwest, living patterns changed in the thirteenth century, with large numbers of people moving into large communal dwellings called puebl os, often constructed at the edges of canyons, especially on the sides of cliffs. Abandoning small extended family households to move into these large pueblos with dozens if not hundreds of other people was probably traumatic. Few of the cultural tradition s and rules that today allow us to deal with dense populations existed for these people accustomed to household autonomy and the ability to move around the landscape almost at will. And besides the awkwardness of having to share walls with neighbors, livin g in aggregated pueblos introduced other problems. For people in cliff dwellings, hauling water, wood, and food to their homes was a major chore. The stress on local resources, especially in the firewood needed for daily cooking and warmth, was particularl y intense, and conditions in aggregated pueblos were not very hygienic. Given all the disadvantages of living in aggregated towns, why did people in the thirteenth century move into these closely packed quarters?",
      "Population growth is considered a particul arly influential push. After several generations of population growth, people packed the landscape in densities so high that communal pueblos may have been a necessary outcome. Around Sand Canyon, for example, population grew from 5 -12 people per square kilometer in the tenth century to as many as 30-50 by the 1200s. As densities increased, domestic architecture became larger, culminating in crowded pueblos. Some scholars expand on this idea by emphasizing a corresponding need for “arable” land to feed grow ing numbers of people: construction of “small dams, reservoirs, terraces, and field houses ” indicates that farmers were intensifying their efforts during the 1200s. Competition for good farmland may also have prompted people to bond together to assert rights over the best fields."
    ],
    "questions": [
      "1. According to paragraph1, before the thirteenth century the people of southwestern North America lived in households that A) shared daily chores with neighboring households B) occupied dwellings that were built into the sides of cliffs C) were largely free to conduct their lives as they pleased D) enforced common standards of behavior and cooperative conduct within their communities",
      "2. According to paragraph, which of the following was one of the consequences of increasing p opulation densities? A) People were increasingly crowded into collections of large housing units. B) People stopped planting crops that have relatively low yields. C) Domestic buildings were pushed beyond the canyon limits. D) The natural landscape was destroyed.",
      "3. The word \"arable\" in the passage is closest in meaning to A. dry B. mountainous C. suitable for farming D. heavily populated",
      "4. Why does the author mention the construction of “small dams, reservoirs, terraces, and field houses”? A. To show evidence that the climate was changing B. To illustrate efforts to manage increased agricultural demands C. To argue that architectural techniques improved over time D. To suggest that the population was decreasing",
      "5. How is the passage organized? A. I t contrasts two different explanations for pueblo construction. B. It presents a cause followed by its effects. C. It lists different types of architecture found in the Sand Canyon area. D. It describes how early farmers migrated to new regions."
    ]
  },
  {
    "id": "r5",
    "title": "리딩 5. Thermoregulation in Marine Organisms",
    "paragraphs": [
      "Living organisms have a variety of ways in which they regulate their body temperature, but they are generally divided into two larger categories. ■Endothermic organisms are those whose metabolisms allow them to maintain a relatively stable temperature that is generally hotter than their ambient conditions. ■The key reason behind the difference is the fact that water is much more conductive than air, and they lose more of their heat into their environment. ■The ma jority of marine creatures regulate their body temperature by matching that of their surroundings, which puts them in the second broad category ectothermic organisms. ■",
      "Most species of fish and invertebrates that “dwell” in the open ocean below tidal areas ectothermic, but not all marine organisms fit neatly into either of the categories. Some organisms possess abilities that allow them to exist somewhere between the two by maintaining a temperature that is higher than the water around them, but well below what truly endothermic creatures are capable of. One such exception is the rapidly swimming fish in the tuna family. They are able to keep their body temperature significantly higher than the water around them through their unique musculature. Unlike most fish whose swimming muscles are distributed evenly under their skin, their red aerobic muscle is located along their spine. This not only makes them powerful swimmers, but it also generates heat at the core of their body. In combination with “a retention system”, this allows them to generate the heat required to increase their metabolic rate and engage in sustained activity."
    ],
    "questions": [
      "1. Look at the four squares [■] that indicate where the following sentence could be added to the passage. The average body temperature of most land mammals tends to be around 40 degrees, but that of marine mammals is usually a few degrees lower Where would the sentence best fit?",
      "2. The word “dwell” in the first sentence is closest in meaning to A. migrate through B. live in C. hide from D. move around",
      "3. According to the passage, how are tuna different from most other fish? A. Their swimming muscles are lo cated under their skin. B. They can live in both freshwater and saltwater environments. C. Their muscles generate heat near the core of their bodies. D. They use their fins to regulate body temperature.",
      "4. What can be inferred about the tuna’s red aero bic muscle? A. It helps produce heat that maintains a higher internal temperature. B. It slows down the tuna’s swimming speed. C. It prevents oxygen from reaching the fish’s brain. D. It is less important for the tuna’s movement than its white muscle.",
      "5. Why does the author mention “a retention system”? A. To show how tuna keep heat from escaping their bodies B. To describe a system that cools tuna muscles during swimming C. To compare tuna to other warm-blooded mammals D. To explain how tuna breathe underwater"
    ]
  },
  {
    "id": "r6",
    "title": "리딩 6. A dust devil",
    "paragraphs": [
      "A dust devil is created when a column of air suddenly heats up relative to the surrounding temperature. Because of heat’s natural tendency to rise, the hot air moves upward as it “displaces” the cooler air around it, spinning rapidly just like water running down a drain. This rotational motion is the most efficient way for fluids to travel through a confined space.",
      "When it first begins to develop the devil is invisible, as only the air is moving but the spinning quickly pick up particles and other debris from the ground and carry them up the vortex giving it a discernable shape and size. Dust devils get their name because these lesser whirlwinds often in areas containing loose dirt of other fragmented materials that are easily carried by the whirlwind. However, they can also arise over water, snow, and even fire. The specific substances transported by the vortex determine the appearance of the devil.",
      "Due to the requirement of heat in the formation of a dust devil, the sun is quite important. Sunny, clear, dry weather with little or no wind offers the prime conditions for the generation of a devil. Deserts are obviously the most common sites of this phenomenon. Heat radiating from the hot, flat sand easily creates the thermally charged columns. Yet, dust devils can occur in any location where the right conditions are present. They range from a few to hundreds of meters in height, with diameters anywhere from tens of meters to less than one. They are typically short lived and do not pose much of a threat."
    ],
    "questions": [
      "1. How does the author explain the movement of heated air in paragraph? a) By contrasting the properties of air and water b) By first describing the movement of cold air c) By explaining the effect a dust devil has on it. d) By comparing it to a more familiar phenomenon",
      "2. According to the passage, what gives a dust devil its visible appearance? A. The rapid heating of the surrounding air B. The presence of sand and debris that the vortex picks up C. The rotation of water vapor in the atmosphere D. The reflection of sunlight off its surface",
      "3. Why does the author mention deserts in the third paragraph? A. To describe an environment where dust devils are most commonly observed B. To explain why dust devils can be dangerous C. To contrast deserts with wetter regions where devils never occur D. To show that dust devils are caused by sandstorms",
      "4. What does the passage suggest about the size and danger of dust devils? A. They can reach enormous siz es and often cause major damage. B. They are small, long-lived, and highly destructive. C. They vary in size but are usually harmless and short-lived. D. They are mostly invisible and harmless because they contain no debris.",
      "5. The word “displaces” in the first paragraph is closest in meaning to A. replaces B. absorbs C. separates D. cools"
    ]
  },
  {
    "id": "r7",
    "title": "리딩 7. Navajo Art",
    "paragraphs": [
      "The Navajo, a Native American people living in the southwestern United States, live in small scattered settlements. For example, the most important traditional Navajo rituals include the production of large floor paintings. These are actually made by pouring thin, finely controlled streams of colored sands or pulverized vegetable and mineral substances, pollen, and flowers in precise patterns on the ground. The largest of these paintings may be up to 5.5 meters in diameter and cover the entire floor of a room. Working from the inside of the design outward, the Navajo artist and his assistants will sift the black, white, bluish-gray, orange, and red ma terials through their fingers to create the finely detailed imagery.",
      "■ The paintings and chants used in the ceremonies are directed by well -trained artists and singers who “enlist“ the aid of spirits who are impersonated by masked performers. ■ The twenty-four known Navajo chants can be represented by up to 500 sand paintings. ■ These complex paintings serve as memory aids to guide the singers during the performance of the ritual songs, which can last up to nine days. ■ The Navajo are also world -famous for the designs on their woven blankets. Navajo women own the family flocks, control the shearing of the sheep, the carding, the spinning, and dying of the thread, and the weaving of the fabrics. While the men who make faithful copies of sand paintings from the past represent the principle of stability in Navajo thought, women embody dynamism and create new designs for every weaving they make. Weaving is a paradigm of the creativity of a mythic ancestor named Spider Woman who wove the universe as a cosmic we b that united earth and sky."
    ],
    "questions": [
      "1. The word “enlist” in the passage is closest in meaning to A. assist B. require C. describe D. recruit",
      "2. What can be inferred from paragraph about the Navajo ritual chants? A. There is a large number of them. B. Each of them corresponds to a particular sand painting. C. They are difficult to remember. D. They do not take long to perform.",
      "3. According to paragraph, all of the following are true of many important Navajo rituals EXCEPT: A. They involve the creation of large, detailed images. B. They include performers whose faces are covered. C. They take place indoors. D. They are performed without elaborate planning.",
      "4. Look at the four squares [■] that indicate where the following sentence could be added to the pa ssage. Since this purpose is limited to the context of the ritual, the paintings are destroyed when the ritual is completed. Where would the sentence best fit?",
      "5. Paragraph 3 supports which of the following statements about Navajo weavers and weaving? A. Navajo women oversee all aspects of wool production and weaving. B. The wool used for blankets comes from different sheep than does the wool used for other purposes. C. Navajo weavers have used some of the same designs for hundreds of years. D. Weaving is done primarily for use in rituals."
    ]
  },
  {
    "id": "r8",
    "title": "리딩 8. Earth’s age",
    "paragraphs": [
      "One of the first recorded observers to surmise a long age for Earth was the Greek historian Herodotus, who lived from approximately 480 B.C. ■He observed that the Nile River Delta was in fact a series of sediment deposits built up in successive floods. ■ By noting that individual floods deposit only thin layers of sediment, he was able to conclude that the Nile Delta had taken many thousands of years to build up. ■ More important than the amount of time Herodotus computed, which turns out to be trivial compared with the age of Earth, was the notion that one could estimate ages of geologic features by determining rates of the processes responsible for such features, and then assuming the rates to be roughly constant over time. ■ Similar applications of this concept were to be used again and again in later centuries to estimate the ages of rock formations and, in particular, of layers of sediment that had compacted an d cemented to form sedimentary rocks.",
      "It was not until the seventeenth century that attempts were made again to understand clues to Earth’s history through the rock record. James Hutton (1726 - 17970), known as the founder of modern geology, was the first t o have the important insight that geologic processes are cyclic in nature. Forces associated with subterranean heat cause land to be uplifted into plateaus and mountain ranges. The effect of wind and water then break down the masses of “uplifted” rock, producing sediment that is transported by water downward to ultimately form layers in lakes, seashores, or even oceans. Over time, the layers become sedimentary rock. These rocks are then uplifted sometime in the future to form new mountain ranges, which exhibit the sedimentary layers (and the remains of life within those layers) of the earlier episodes of erosion and deposition.",
      "Hutton’s concept represented a remarkable insight because it unified many individual phenomena and observations into a conceptual p icture of Ea rth’s history. With the further assumption that these geologic processes were generally no more or less vigorous than they are today, Hutton’s examination of sedimentary layers led him to realize that Earth’s history must be enormous, that “geologic time” is an abyss, and human history is only a speck by comparison."
    ],
    "questions": [
      "1. According to paragraph, Herodotus’ observations of the Nile River Delta were significant because they allowed him to a) provide detailed records of the most significant floods in the history of the Nile. b) develop a way of calculating the age of geologic features c) conclude that the Nile River Delta was as old as Earth d) predict when the river would flood and when it would not",
      "2. Look at the four squares [■] that indicate where the following sentence could be added to the passage. This idea came to be known as the principle of uniformitarianism, and Herodotus was only the first to apply it. Where would the sentence best fit?",
      "3. According to paragraph, James Hutton was th e first person to a) understand clues to Earth’s history through the rock record b) work out principles of the progressive depositing of sediment c) realize that geologic processes happen in cycles d) describe the forces associated with subterranean heat",
      "4. The word “uplifted” in the first paragraph is closest in meaning to A. eroded B. raised C. cooled D. dissolved",
      "5. What does Hutton’s conclusion about “geologic time” suggest? A. The Earth is far older than people of his time believed. B. Geological change happens quickly in human history. C. Human civilization caused most geological formations. D. Earth’s age could be measured precisely in centuries."
    ]
  },
  {
    "id": "r9",
    "title": "리딩 9. Transition to Sound in Film",
    "paragraphs": [
      "The shift from silent to sound film a t the end of the 1920s marks, so far, the most important transformation in motion picture history. Despite all the highly visible technological developments in theatrical and home delivery of the moving image that have occurred over the decades since then, no single innovation has come close to being regarded as a similar kind of watershed. In nearly every language, however the words are phrased, the most basic division in cinema history lies between films that are mute and films that speak.",
      "Yet this most fundamental standard of historical periodization conceals a host of paradoxes. Nearly every movie theater, however modest, had a piano or organ to provide musical accompaniment to silent pictures. In many instances, spectators in the era before recorded so und experienced elaborate aural presentations alongside mo vies' visual images, from the Japanese benshi (narrators) crafting mult ivoiced dialogue narratives to original musical comp ositions performed by symphony-size orchestras in Europe and the United Sta tes. In Berlin, for the premiere performance outside the Soviet Union of The Battleship Potemkin, film director Sergei Eisenstein worked with Austrian composer Edmund Meisel (1874- 1930) on a musical score matching sound to image; the Berlin screenings with live music helped to bring the film its wide international fame.",
      "Beyond that, the triumph o f recorded sound has ★ overshadowed ★ the rich diversity of technological and aesthetic experiments with the visual image that were going forward simultaneously in the 1920s. New color processes, larger or differently shaped screen sizes, multiple screen projections, even television, were among the developments invented or tried out during the period, sometimes with startling success. The high costs of converting to sound and the early limitations of sound technology were among the factors that suppressed i nnovations or retarded advancement in these other areas. The introduction of new screen formats was put off for a quarter century, and color, though utilized over the next two decades for special productions, also did not become a norm until the 1950s."
    ],
    "questions": [
      "1. The word “watershed” in the first paragraph is closest in meaning to A. disaster B. turning point C. discovery D. movement",
      "2. According to the passage, what feature distinguished silent films from sound films? A. Silent films had smaller screens and no music. B. Silent films were made only in black and white. C. Silent films lacked recorded dialogue and sound. D. Sound films were shorter and less expensive to produce.",
      "3. What can be inferred about movie theaters before the introduction of sound films? A. They often used live music or narration to accompany the films. B. They were unable to provide any kind of sound experience. C. They preferred to show foreign films to attract larger audiences. D. They only showed films directed by famous composers.",
      "4. W hat was the role of Edmund Meisel in the premiere of The Battleship Potemkin in Berlin? A. He designed the film’s visual effects. B. He composed music to accompany the film’s images. C. He worked as a benshi narrator for the screenings. D. He directed the film’s international release.",
      "5. What does the passage suggest about the impact of recorded sound on other film innovations? A. It encouraged the development of new visual techniques. B. It slowed progress in areas like color and screen design. C. It led to the immediate adoption of color technology. D. It made television obsolete for decades."
    ]
  },
  {
    "id": "r10",
    "title": "리딩 10. The Life Cycle of Stars",
    "paragraphs": [
      "We naturally assume that there are countless stars in the universe. But we don’t have specific numbers in our head. Astronomers very conservatively estimate that there are 10 sextillion stars in the universe. This number is the product of 100 billion Χ 100billon. However, the way in which these stars evolve is fairly similar. Modern astronomical observation, coupled with nuclear theory, has led scientists to a simple theory involving our stellar universe. Through careful observation, scientists have discovered that there are hundreds of types of stars and that they all follow a standard life cycle; scientists believe that this cycle applies to every known star.",
      "All stars begin as protostars, which consist of “concentrations” of luminous gas found within large diffused clouds of dust and gas. As they mature, protostars collapse inward under their own gravity, compressing their core until hydrogen-fusion reactions result in ignition. When this happens, the protostar is said to be on the main sequence, or a diagonal track. Many stars remain on this track for billions of years.",
      "During the “main sequence” phase, stars similar in mass to the sun burn hydrogen, which is converted into helium. Eventually, the hydrogen in the star’s center is depleted so that the necessary radiation to balance gravity is lost. At this point, the center of the star contracts until it is hot enough for the helium to be converted into carbon. The remaining hydrogen continues to burn and is converted to hel ium, but the outer layers of the star have to expand to conserve energy. After the supply of hydrogen runs out, the star enters the next phase of its evolution. At this time in the star’s life cycle, the star “appears brighter ” and it is known as a red giant."
    ],
    "questions": [
      "1. The word “concentrations” in the second paragraph is closest in meaning to A. mixtures B. clusters C. reactions D. solutions",
      "2. According to the passage, what causes a protostar to become a main-sequence star? A. The formation of dust clouds around it B. The burning of helium into carbon C. The collapse of the core until hydrogen fusion begins D. The cooling of its outer layers",
      "3. What can be inferred about the “main sequence” mentioned in the passage? A. It is the shortest stage in a star’s life cycle. B. It represents a period of relative stability for most stars. C. It is a rare phase experienced only by massive stars. D. It marks the final stage before a star becomes a black hole.",
      "4. What happens when the hydrogen in a star’s center is used up? A. The star cools and stops shining immediately. B. The core contracts and begins fusing helium. C. The star collapses into a black hole. D. The outer layers are ejected into space.",
      "5. Why does the author mention that stars “appear brighter” when they become red giants? A. To show that they are closer to Earth than before B. To explain how they conserve their remaining energy C. To illustrate one of the visible changes during a star’s evolution D. To suggest that red giants are a new kind of star"
    ]
  },
  {
    "id": "r11",
    "title": "리딩 11. Functions of roots",
    "paragraphs": [
      "One of the most important functions of root networks is to provide a stable footing for plants so they do not fall over or get swept away This also provides the secondary benefit of controlli ng soil erosion around the plant's base . In addition to this, many plants like the carrot and turnip also store nutrients in modified roots. Roots of plants such as the “bluebell” store so much energy that they act as “perennating” organs allowing the plant to survive harsh conditions such as drought, frigid winters, or light deficiency. They do this by allowing the exposed part of the plant to die down and storing as much energy as possible for regrowth when conditions improve.",
      "For plants which are consta ntly exposed to harsh environments, such as salt water swamps, survival is more challenging due to the lack of basic necessities. The deeper roots of most plants die because of the lack of oxygen under the waterlogged soil, leading to the plant's slow deat h. Mangrove roots, however, are well-suited to the region. The “red mangrove” , a tropical tree which colonizes coastlines and brackish water between the northern and southern latitudes of 25 degrees, can often be found on the water's edge.",
      "These are distinguished from other mangroves by the prominent prop roots extending into t he water from high up on their stems. They thrive in the highly saline habitats by not relying on traditional roots growing under the substrate,' Instead, it is assumed, lenticels, or pores, on their prop roots act as conduits for supplying oxygen for respiration' to the subterranean roots. Unlike most plants, their roots also enable them to obtain freshwater from highly saline water sources through non-metabolic ultra -filtration, usin g negative pressure inside the root to draw freshwater in through a membrane too fine for salt to pass through, in a process called reverse-osmosis."
    ],
    "questions": [
      "1. The word “perennating” in the first paragraph is closest in meaning to A. storing nutrients for seasonal regrowth B. spreading seeds over a wide area C. absorbing water from soil D. providing structural support",
      "2. According to the passage, what is one main function of roots in most plants? A. To help the plant reproduce quickly B. To prevent the plant from being uprooted and reduce soil erosion C. To convert saltwater into freshwater D. To allow the plant to grow without sunlight",
      "3. Why does the author mention “bluebell” in paragraph? (A) To show how plant footing also prevents erosion (B) To give an exam ple of a harsh environment in which modified roots store nutrients. (C) To explain how energy stored in roots allows for long-term plant survival (D) To illustrate that plants regrow when conditions",
      "4. Which of the following is true about the habitats o f the red mangrove? (A) They are inland areas of the northern and southern hemisphere. (B) They are favorable places in which a variety of plants grow and adapt. (C) They are devoid of plant life due to their high temperatures (D) They lack the essential needs of other plants.",
      "5. According to paragraph, how do red mangroves survive in their environment? (A) The roots of the mangrove are able to expel the salt it has absorbed. (B) The mangrove has roots that separately absorb water and salt. (C) Lenticels on the prop roots provide oxygen to the subterranean roots. (D) The salinity of water lessens as it passes through a strainer in the stem."
    ]
  },
  {
    "id": "r12",
    "title": "리딩 12. Age of bats",
    "paragraphs": [
      "Several other methods have been developed to determine the biological age of bats. The first measures the long bones, like the forearm, metacarpals, and digits, which go through a phase of rapid linear growth shortly after birth. These measurements, especially that of the forearm, can be used to distinguish ju veniles from adults. The major disadvantage is that these bones grow only during the first few weeks of life and the valid time frame varies between species from only 12 days in M. lucifugus to as long as 45 days in R. l eschenaulti. Other traits, such as changes in the patterns and rates of closure of the cartilaginous epiphyseal growth plates are, therefore, necessary to estimate the age of older individuals. In its simplest form, this method distinguishes between young bats and adults. By transilluminatin g the wing of a juvenile, a researcher can discern the cartilaginous zone of the long phalanges which allows more light to pass through and thus appears lighter than bone. As the bat continues to grow, the epiphyseal plates eventually close and are no long er visible to the unaided eye. This method of age categorization requires no more than a flashlight and is ideal for use in both the field and the laboratory.",
      "Another method of estimating bats' age is to study their teeth. Much like puppies that lose thei r sharp baby teeth before growing a set of permanent adult teeth, in most bat species, permanent teeth replace the deciduous ones by the time “juveniles” are able to fly and feed independently. Once in place, these permanent teeth reach full size and cease to grow. A lifetime of mastication however wears down their surfaces and erodes their enamel. The degree of tooth wear can, therefore, be used to place bats into relative age categories as this process occurs from weaning until death. Due to differences i n diet, tooth usage in aggressive interactions, and the populations annual activity periods, species show significant variation in tooth wear. Therefore, the development of species - specific reference standards based on a wide -ranging sample of known -age i ndividuals is critical for the proper use of this me thod, as are investigators with extensive species -specific experience assessing tooth wear."
    ],
    "questions": [
      "1. What can be inferred from paragraph about the cartilaginous epiphyseal growth plate? (A) It is the easiest e xternal physical characteristic for accurately measuring bats' age throughout its lifetime (B) It is possible to determine the adult bat's age by looking at its mineralized bone tissue (C) Changes in the pattern and rate of closure happen due to linear growth in adult long bones. (D) Light can no longer penetrate it because it shuts as the bat gets older.",
      "2. why does the author mention the teeth of puppies? (A) To show that dogs' ages can also be measured through their teeth (B) To show the similarity o f the growth of teeth with bats (C) To illustrate the high degree of accuracy of age measurement using teeth (D) To support the claim that dogs live longer than bats due to their healthy teeth",
      "3. According to paragraph, what is true about bat's teeth? (A) The age of bats can be determined by the degree at which their teeth are angled regularly. (B) Bats experience continuous tooth growth until death. (C) Through their size, it is possible to know the bat's exact age. (D) When bats become adults, they wi ll have blunter teeth.",
      "4. Why does the author mention the differences in diet, tooth usage in aggressive interactions, and populations' annual activity periods? (A) To illustrate the bats' life cycle as they grow older (B) To give some reasons that a spec ies-specific reference standard was required to determine bats' ages (C) To provide evidence that adult bats live in wild habitats (D) To show the main seasons in which adult bats' teeth are worn.",
      "5. The word “juveniles” in the second paragraph is closest in meaning to A. mixtures B. immature individuals C. reactions D. solutions"
    ]
  },
  {
    "id": "r13",
    "title": "리딩 13. Mating Calls of the Tungara frogs",
    "paragraphs": [
      "The most fundamental of the tungara frogs mating vocalizations is a descending , high -frequency sweep referred to as a whine, Simple calls consist of a whine only, and they are probably sufficient to attract a female when the caller does not face significant competition from other males. However, when many frogs concentrated in one area are contending for a mate, these types of calls are often insufficient. Thus, male tungara frogs have developed a second type of vocalization that they can add in an attempt to stand out from the crowd. These grunts, often called chucks, are made possible by the presence of “large, fibrous masses” in the frogs' larynxes. A male generates a chuck by moving air in and out of its vocal sa c, a process that creates a series of ripples in the water, and these aquatic vibrations may also aid in making it easier for females to locate their prospective mates.",
      "According to scientific studies, calls that include at least one chuck on average are five times appealing to females than calls that do not, and calls with multiple chucks seem to be more attractive than those with just one. Therefore, it is sexually advantageous for male frogs to make more elaborate calls. ■ Moreover, researchers have discovered that females prefer chucks that are low in frequency, perhaps because these sounds tend to be produced by males with larger bodies. ■ Large male frogs are likely to be of “superior” genetic quality, and they achieve higher rates of egg fertilization since females tend to be bigger than males and fertilization rates are correlated with similarity in size between the two members of a mating pair. ■ Still, some researchers have taken issue with the idea that females pref er these males because they are better mates, and they contend that the females are selecting these mates simply because they are easier to find due to the fact that they emit a greater number of clearly audible calls. ■ Even if this is correct, however, i t is plausible that the females are still gaining a selective advantage if this same trait -the tendency to use multiple chucks - is passed on through heredity her offspring as they too would have a higher likelihood of finding a mate and passing on their genes."
    ],
    "questions": [
      "1. Which of the following is stated about simple calls in paragraph? (A) They are helpful when males want to stand out against background noise, (B) They are usually inadequate when competing males are present (C) They create ripples in the water t hat are attractive to females. (D) They generate sound waves that are inaudible to females.",
      "2. Why does the author mention \"large, fibrous masses”? (A) To explain how a túngara frog is able to produce chucks (B) To emphasize the impressive size of the v ocal organs of tungara frogs (C) To highlight an anatomical characteristic that is absent in young males (D) To point out a physical feature that is attractive to females",
      "3. According to paragraph , what is a possible explanation for why female túngara frog s prefer low - frequency sounds? (A) They demonstrate that the male is larger than the female (B) They communicate that the male wishes to mate. (C) They are indicative of the caller's body size. (D) They signal that many frogs are present in one place.",
      "4. Look at the four squares [ ■] that indicate where the following sentence could be added to the passage This explanation has some value because, in general, low-frequency sounds indeed travel further than ones that are higher in frequency. Where would the sentence best fit?",
      "5. The word “superior” in the second par agraph is closest in meaning to A. healthier than B. better than C. bigger than D. more expensive than"
    ]
  },
  {
    "id": "r14",
    "title": "리딩 14. ADA LOVELACE",
    "paragraphs": [
      "Ada Lovelace was an English mathematician and writer who is most n oted for her work on Charles Babbage's Analytical Engine, a mechanical general -purpose computer that was never built Lovelace recognized the potential of the machine and “foresaw” its capabilities for more than just mathematical calculations. She wrote the first algorithm designed for the machine and is recognized as the world's first computer programmer. Lovelace was born on December 10, 1815, in London, England. She was the only legitimate child of Lord Byron, a renowned poet, and his wife, Anne Isabella Milbanke. Byron separated from his wife only a few weeks after Ada's birth and left England.",
      "Milbanke raised Ada with a strong emphasis on mathematics and logic, hoping to suppress any creativity that she believed her daughter might have inherited from her father. As a teenager, Lovelace developed a strong interest in mathematics and logic, and she met Charles Babbage, a mathematician and inventor, through her husband. Babbage had designed the Difference Engine, a mechanical calculator, and was working on his more advanced machine, the Analytical Engine. Lovelace recognized the potential of the machine and began working with Babbage, becoming his collaborator and friend.",
      "In 1843, Lovelace translated an article about the Analytical Engine by an Italian engi neer and added her own notes, which were three times longer than the original article. Her notes included a sequence of operations, or algorithm, that could be carried out by the machine, demonstrating that the machine could be used for more than just math ematical calculations. Her work was groundbreaking and visionary, and her algorithm is recognized as the first computer program.",
      "Lovelace's insights were remarkable, as she was able to conceive the idea of using the Analytical Engine for more than just si mple calculations. She recognized that it could be programmed to perform a variety of tasks, including composing music and producing graphics. This was an astounding insight at the time, as people thought of machines only as tools for mathematical calculation."
    ],
    "questions": [
      "1. What is Ada Lovelace most noted for? (a) developing various uses of the computer (b) working on a programmable machine (c) creating the Analytical Engine (d) contributing to the field of mathematics",
      "2. Why did Lovelace's mother expose her to mathematics and logic? (a) to prepare her for a career in science (b) to help her meet influential people (c) to discourage her imaginative tendencies (d) to follow the wishes of her absent father",
      "3. According to paragraph, how did Lovelace meet Charles Babbage? (a) She worked with him on an invention. (b) She began studying mathematics with him. (c) She was introduced to him by her family. (d) She contacted him about the Difference Engine.",
      "4. Why most likely did Lovelace contribute additional notes to the translated article? (a) She struggled to translate the Italian writing to English. (b) Readers needed more information about the Analytical Engine. (C) She wanted to add her original ideas to the article (d) The Analytical Engine was widely misunderstood.",
      "5. The word “foresaw” in the second par agraph is closest in meaning to A. suspected B. conveyed C. anticipated D. observed"
    ]
  },
  {
    "id": "r15",
    "title": "리딩 15. KARL MARX",
    "paragraphs": [
      "Karl Marx was a German philosopher, economist, and political theorist, cons idered one of the most influential figures in the history of socialism and communism. He is best known for his works on capitalism, the labor theory of value, and his critique of political economy. In 1843, Marx moved to Paris, where he met Friedrich Engel s, who became his lifelong friend and collaborator. Together, they wrote The Communist Manifesto (1848), which became one of the most influential political texts in history.",
      "In his most famous work, Das Kapital (1867), Marx analyzed the economic system o f capitalism, arguing that it was inherently exploitative and would inevitably lead to revolution. He also introduced the concept of the labor theory of value, which argued that the value of a commodity is determined by the amount of labor that goes into p roducing it. This idea had a profound influence on the development of Marxist economics.",
      "Marx was also an important political activist, “advocating” for the overthrow of the ruling class and the establishment of a socialist society. He believed that the w orking class, or the proletariat, would eventually rise up against their oppressors and take control of the means of production. Marx's ideas had a profound impact on the course of world history, with many countries adopting Marxist principles to varying degrees. The Soviet Union, China, and Cuba all claimed to be following Marxist -Leninist principles, and Marxism played a significant role in the decolonization movements of the mid -20th century.",
      "However, Marx's ideas have also been heavily criticized, particularly for their association with authoritarianism and the suppression of individual freedoms."
    ],
    "questions": [
      "1. What is Karl Marx most famous for? (a) developing a theory of authoritarianism (b) challenging a law that limited workers' rights (c) leading several revolutions around the world (d) proposing theories about capitalism and labor",
      "2. How most likely did Engels influence Marx's work? (a) by introducing him to the work of Hegel (b) by writing a political statement with him (c) by encouraging him to study philosophy (d) by collaborating on some political essays",
      "3. According to the article, what was the topic of Das Kapital? (a) the imbalance in capitalist systems (b) a proposal for a peaceful revolution (c) an examination of capitalism's virtue (d) the inevitability of class hierarchy",
      "4. Based on the third paragraph, which of the following is NOT true about Marx? (a) He believed the working class would revolt. (b) He supported the development of a socialist society. (c) He wanted the working class to possess the means of production. (d) He argued that the ruling class should be protected from the overthrow.",
      "5. The word “advocating” in the second par agraph is closest in meaning to A. continuing B. challenging C. arguing D. working"
    ]
  },
  {
    "id": "r16",
    "title": "리딩 16. PROSCIUTTO",
    "paragraphs": [
      "Prosciutto is the generic term for an Italian dry -cured ham. Characterized by a sweet, delicate flavor, it is often served thinly sliced and raw in a style known as prosciutto crudo. The curing process makes the raw ham safe to eat. When it is served cooked, it is called prosciutto cotto. The most famous prosciutto variety is Prosciutto di Parma PDO, which comes from the Emilia -Romagna region in Italy's north. The PDO designation stands for Protected Designation of Origin and signifies t hat the product is authentic and meets certain standards of quality.",
      "Regardless of origin, all prosciuttos are made from the hind leg or thigh of an animal. In most cases, the animal is a pig or a wild boar. However, prosciutto may also be made using othe r animals, in which case the animal must be identified in the product's name, as in prosciuto cotto d'agnello, or lamb prosciutto. To make prosciutto, the ham is first cleaned, salted, and left for two months. During this time, it is gradually pressed to drain all blood left in the meat.",
      "This must be done carefully to avoid breaking the bone. Next, the ham is washed and hung in a dark, well-ventilated environment. The surrounding air is important to the ham's final quality. It needs to be damp but cool to prevent spoilage. The duration of the drying process varies based on local climate and the ham's size. Once dry, it is placed on a hook to air, either at room temperature or in a temperature - controlled environment, for as long as 18 months.",
      "Some manufactur ers cure the ham with sodium or potassium nitrites, which “increases” the quality of its salty flavor. Others use only sea salt."
    ],
    "questions": [
      "1. How does prosciutto cotto differ from prosciutto crudo? (a) It is cured. (b) It is cooked. (c) It is moister. (d) It is cut into thick slices",
      "2. What is ltaly's Emilia-Romagna region known for? (a) being the birthplace of prosciutto crudo (b) consuming the largest quantities of prosciutto (c) producing the best known variety of prosciutto (d) establishing standards for prosciutto production",
      "3. What is similar about all varieties of prosciutto? (a) the time it takes to make (b) the kind of salt they contain (c) the part of the animal that is used (d) the age of the pigs they come from",
      "4. Which is NOT a step in the process of making prosciutto? (a) washing in salt water (b) hanging in a darkened room (C) extracting blood from the meat (d) exposing to air for several months",
      "5. The word “increases” in the second paragraph is closest in meaning to A. lowers B. improves C. recovers D. solidifies"
    ]
  },
  {
    "id": "r17",
    "title": "리딩 17. DIVING",
    "paragraphs": [
      "Diving is the sport of plunging into water from a platform or springboard, usually while d performing acrobatics. Although diving contests were held in England in the 1800s, it was not until 1903 that it formally became a competitive sport. I t was added to the Sum mer Olympic Games a year later. The sport originated in Europe in the early 1800s. It allowed gymnasts to perform elaborate acrobatic feats without fear of injury from impact with the ground. Even today, gymnasts are particularly “disposed” to becoming professional divers, and many do. Both sports have similar requirements for strength, flexibility, and the ability to judge one's position while moving through the air.",
      "In diving competitions, dives are performed from a 5 - or 10-meter platform and a 1- or 3-meter springboard. Only the 10 -meter dive and 3 -meter dive are used in the Olympics. In either case, divers must complete 10 dives in sequence from a list they prepare and submit beforehand. Judges rate divers based on how they accomplish each part of a div e, beginning with the takeoff or hurdle, then the flight or actual dive, and lastly the entry, or how the diver hits the water. The resulting score is multiplied by a degree of difficulty factor based on the number and combination of movements attempted.",
      "At the highest levels of competition, degree of difficulty is less important than how a sequence of dives is arranged since divers all have about the same level of skill. The only way to gain an edge is to complete each dive as perfectly as possible. Consequently, divers adopt a strategy of organizing dives by level of personal comfort. This allows them to build up confidence and momentum as the competition progresses."
    ],
    "questions": [
      "1. When did diving become an Olympic sport? (a) in the early 1900s (b) toward the end of the 1800s (c) during the 19\"h century (d) in the middle of the 1900s",
      "2. According to the passage, why did diving initially appeal to gymnasts? (a) Gymnasiums were often built near pools. (b) Moving through water helped them build strength. (c) Their powerful leg muscles were suitable for diving (d) Swimming pools provided a soft landing.",
      "3. What must divers do when they participate in an Olympic competition? (a) register for membership in an organization (b) choose from one of two diving platforms (c) finish 10 dives from a list they hand in (d) complete at least one dive from every category",
      "4. How are divers scored in competitive diving? (a) The divers' scores are determined by the number of movements and difficulty. (b) Divers are given a score that is divided by how many dives they did. (c) The judges give each diver a score out of 100. (d) Divers are scored based on the height of the board they jump from. 5, In the context of the passage, “disposed” means (a) biased (b) removed (c) inclined (d) arranged"
    ]
  },
  {
    "id": "r18",
    "title": "리딩 18. MONOPOLY",
    "paragraphs": [
      "Monopoly is a real -estate board game in which individuals compete for control of properties, which they use to bankrupt opponents and dominate the game. Published by Hasbro, it is the best -selling privately patented board game in history. The game is named for the economic concept whereby a single company maintains total control of a market. Itis derived from an earlier board game called The Landlord's Game, created in 1903 by Lizzie G.",
      "Magie. Magie's game grew popular enough that others d evised homemade variations to play with friends. Charles B. Darrow, intrigued by one of these versions, modeled his own and called it Monopoly. From 1933 to 1934, he successfully marketed his game to retailers. Unfortunately, game sales exceeded his production capacity and he sold the rights to Parker Brothers in 1935. To play the game, players start with a fixed amount of play money issued by a designated banker. They roll a pair of dice to see who goes first and to move game pieces around the board. Along the way, players buy up vacant properties, which they may trade to complete matching sets. Having a completed set creates a monopoly and means improvements like houses or hotels can be added. Players must pay rent on properties occupied by an opponent, an d rents go up with every improvement, Players who cannot afford the payments eventually go bankrupt and are removed from the game. The game continues until one player remains. The board also features event squares that instruct players to perform specific tasks.",
      "Despite involving elements of strategy and negotiation, Monopoly has earned criticism for its game mechanics. Many games take too long to finish. In addition, the game's dependence on chance means one or two lucky players accumulate resources early on and become runaway leaders,\" players who advance so quickly that others have no way of catching up. Still, the game has become a mainstay in homes around the world, spawning hundreds of editions. In the original sets, properties were named for streets i n Atlantic City, New Jersey. In some countries, these and other features may be altered to suit the local market."
    ],
    "questions": [
      "1. What is the object of the game in Monopoly? (a) to dominate a property market (b) to earn the most money per round (c) to endure until all opponents give up (d) to build a fixed number of houses",
      "2. Where did Darrow most likely get the idea for Monopoly? (a) from being introduced to Lizzie Magie (b) from playing an early version with friends (c) from creating The Landlord's Game (d) from working briefly at Parker Brothers",
      "3. Which is true about the way Monopoly is played? (a) Whoever has the most money goes first. (b) Designated bankers use a special game piece. (c) Only properties in complete sets can be improved. (d) Players draw cards to move around",
      "4. What are \"runaway leaders\"? (a) players who develop a big lead early in a game (b) players who leave a game despite being ahead (c) players who refuse to quit no matter how long it takes (d) players who always seem to come in second place",
      "5. How is Monopoly probably different in other countries? (a) Players use real money. (b) The game board is larger. (c) There are fewer game pieces. (d) Street names are changed."
    ]
  },
  {
    "id": "r19",
    "title": "리딩 19. DAVID FINCHER",
    "paragraphs": [
      "David Fincher is an American producer and director working in film, television, and music. With numerous nominations and awards over the span of three decades, Fincher has achieved fame for his continuous pursuit of perfection and rem ains one of the most sought-after figures in Hollywood. When Fincher was two years old, his family moved to a small town outside San Francisco, where he first developed an interest in film after catching a screening of the immensely successful American western, Butch Cassidy and the Sundance Kid. Fincher began making home movies with an 8 mm film camera shortly thereafter. As a teenager, Fincher resided in Ashland, Oregon, where he participated in numerous extracurricular activities associated with filmmaking, such as directing school plays, working as a projectionist at a movie theater, and taking a job as a production assistant at a local television news station.",
      "Fincher began to realize his dream of a professional film career in the early 1980s, when he was hired as an assistant cameraman for visual effects company Industrial Light & Magic, then owned by George Lucas, the creator of Star- Wars. He worked on the hit movie Indiana Jones and the Temple of Doom, and was commissioned to direct a television ad for the American Cancer Society. In the ad, he shocked viewers by depicting a human fetus smoking a cigarette in its mother's womb. This boldness attracted attention from Hollywood producers. and the recognition prompted Fincher to co -found Propaganda Film s in 1986, a video -production company that produced many successful films and music videos between 1990 and 2002.",
      "Fincher's success only grew from there, and he has since won substantial praise and recognition from his industry peers. A crowning achievemen t has been winning a Golden Globe for his direction of The Social Network, a film about the development of Facebook."
    ],
    "questions": [
      "1. What is David Fincher most famous for? (a) receiving many nominations and awards (b) his early interest in directing films (c) being highly desired in Hollywood (d) his constant quest for perfection",
      "2. What inspired Fincher to become a filmmaker? (a) watching a hit movie (b) working with his parents (c) growing up in San Francisco (d) receiving a camera as a gift",
      "3. Which is not true about Fincher in his youth? (a) He directed plays for his school. (b) He was employed at a movie theater. (c) He filmed his first commercial movie. (d) He assisted at a TV news station.",
      "4. What made producers in Hollywood notice Fincher? (a) his work at Industrial Light & Magic (b) making a controversial TV commercial (c) his role in the Indiana Jones movie (d) opening his own successful film company",
      "5. According to the article, what is considered Fincher's highest professional achievement? (a) winning a Golden Globe for best director (b) directing the 21st century's top music video (c) producing the most Oscar-nominated actors (d) making one of the first movies about Facebook"
    ]
  },
  {
    "id": "r20",
    "title": "리딩 20. THE COOPER'S HILL CHEESE-ROLLING AND WAKE",
    "paragraphs": [
      "The Cooper's Hill Cheese-Rolling and Wake is a world- famous event in which groups of competitors’ chase cheese down an extremely steep hill Itis best known for being very dangerous, with competitors often needing medical attention. There ar e two competing theories for why the race originally began, neither of which has been proven. Some people claim that holding it was a way of maintaining grazing rights for animals on Cooper's Hill, while others believe that it was connected to the pre - Christian pagan ritual of rolling bundles of burning brushwood down the hill. The first historical evidence of the race being held comes from an 1826 message received by the Gloucester town crier, but the tradition was known to already be very old by that point.",
      "The race features a seven to nine pound circle of Double Gloucester cheese, which, since 1988, has been supplied by cheese maker Diana Smart. The cheese must be encased in wood and decorated with ribbons before a master of ceremony rolls it down the 200-yard, 1:2-gradient hill to start the race. Once the cheese is released the racers run after it and either try to catch it, or be the first to follow it to the bottom of the hill. The cheese can reach speeds of 70 miles per hour, making it potentially dan gerous for spectators, so a lightweight foam stand -in has been used instead in some year s. Winners of the race are real awarded real cheese.",
      "The steepness of the hill and the speed at which the cheese rolls down it, make injuries a common occurrence in the race. After 15,000 spectators came to the event in 2009, it was canceled by the authorities in 2010 . However, local people soon restarted the tradition and now organize the event without any official assistance."
    ],
    "questions": [
      "1. What is the Cooper's Hill Cheese-Rolling and Wake best known for? (a) It is the only cheese-rolling event in England. (b) It is held on the steepest hill in the UK. (c) It is extremely hazardous to participants. (d) It is one of the oldest pagan ceremonies.",
      "2. Why most likely does no one know why 19. the cheese-rolling event started? (a) The race was not recorded by the Gloucester town crier. (b) The race was started by Christians from other regions. (c) The race began a long time ago. (d) The race was considered to be against the law.",
      "3. What should be done before the race can begin? (a) the consecration of the cheese by a priest (b) the adornment of the cheese with ribbons (c) the town crier's announcement of the start (d) the cheese handed over to the participants",
      "4. Why was the cheese replaced by a foam stand-in? (a) because the race was considered too fast (b) because the organizers wanted to maintain the cheese (c) because racers could not catch the cheese (d) because the cheese could have harmed spectators",
      "5. What was probably the reason local people started to organize the race? (a) The hill's owner stopped people from racing. (b) The safety issues meant few people came. (c) The race lost its financial backing. (d) The event was officially canceled."
    ]
  }
];
